name: Labeling new issue
on:
  issues:
    types: ["opened"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.3.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"bug":["error","need fix","not working"],"enhancement":["upgrade"],"question":["help"]}'
          labels-not-allowed: '["good first issue","needs priority","testing","wontfix"]'
          default-labels: '["help wanted"]'
